version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  cartonscraping:
    build:
      context: scraping
      dockerfile: Dockerfile
    environment:
      - DB_DB=${DATABASE_NAME}
      - DB_HOST: db
      - DB_PORT=5432
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '8085:8085'
    image: cartonscraping
    links:
      - db

  cartonback:
    build:
      context: back
      dockerfile: Dockerfile
    environment:
      - DB_DB=${DATABASE_NAME}
      - DB_HOST: db
      - DB_PORT=5432
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '8080:8080'
    image: cartonback
    links:
      - db

  cartonfront:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - API_URL: cartonback
    ports:
      - '8081:4200'
    image: cartonfront
    links:
      - cartonback

volumes:
  db:
    driver: local
